name: Despliegue pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Instalar dependencias
        run: npm install
      - name: Comprobar estilo
        run: npm run eslint
      - name: Comprobar build
        run: npm run build
      - name: Comprobar tests
        run: npm run test

      - name: e2e tests
        run: | 
          npm run start-prod &
          sleep 15
      - name: Instalar dependencias e2e
        run: npm install
        working-directory: ./e2e-tests
      - name: Instalar navegador de playwright
        run: npx playwright install --with-deps
        working-directory: ./e2e-tests
      - name: Comprobar e2e tests
        run: npm run test
        working-directory: ./e2e-tests

      - name: Deploy
        # Only run this step if the branch is main and the commit not contains #skip
        if: github.ref == 'refs/heads/main' && !contains(join(github.event.commits.*.message, ' '), '#skip')
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: | 
          curl "$deploy_url"
  
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        if: github.ref == 'refs/heads/main' && !contains(join(github.event.commits.*.message, ' '), '#skip')
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch